# Default values for the Migration Toolkit for VMs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: mtv-operator
  namespace: openshift-mtv

spec:
  channel: release-v2.6
  installPlanApproval: Automatic
  startingCSV: mtv-operator.v2.6.2
