# Default values for ACM.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: advanced-cluster-management
  namespace: open-cluster-management

spec:
  channel: release-2.8
  installPlanApproval: Automatic
  startingCSV: advanced-cluster-management.v2.8.3
