kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin
  namespace: demo-project
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: demo-project
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
