apiVersion: forklift.konveyor.io/v1beta1
kind: ForkliftController
metadata:
  name: forklift-controller
  namespace: openshift-mtv
spec:
  olm_managed: true
  feature_must_gather_api: 'true'
  feature_ui: 'false'
  feature_ui_plugin: 'true'
  feature_validation: 'true'
  feature_volume_populator: 'true'
  
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-wave-delay-
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: wait-pod
        image: perl
        command: ["sleep",  "180"]
      restartPolicy: Never
