apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-migration
  namespace: openshift-mtv
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  targetNamespaces:
    - openshift-mtv
