# Default values for lvm-storage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: lvms-operator
  namespace: openshift-storage

spec:
  channel: stable-4.13
  installPlanApproval: Automatic
  startingCSV: lvms-operator.v4.13.1