kind: Project
apiVersion: project.openshift.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    argocd.argoproj.io/managed-by: "openshift-gitops"
  name: dev-env
spec: {}
