kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: bgd
  namespace: dev-env
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: bgd
spec:
  host: bgd-dev-env.apps.hubcluster.sandbox991.opentlc.com
  to:
    kind: Service
    name: bgd
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
