kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: bgd
  namespace: dev-env
  annotations:
    argocd.argoproj.io/hook: PostSync
  labels:
    app: bgd
spec:
  host: bgd.apps.sno.homelab.com
  to:
    kind: Service
    name: bgd
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
