apiVersion: v1
kind: Service
metadata:
  labels:
    app: bgd
  name: bgd
  namespace: demo-project
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bgd
