apiVersion: v1
kind: Service
metadata:
  labels:
    app: bgd
  name: bgd
  namespace: dev-env
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "3"
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bgd
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-wave-delay-
  namespace: dev-env
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: wait-pod
        image: perl
        command: ["sleep",  "60"]
      restartPolicy: Never
