apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-wave-delay-
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: wait-pod
        image: perl
        command: ["sleep",  "300"]
      restartPolicy: Never
