apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: {{ .Values.spec.channel }}
  installPlanApproval: {{ .Values.spec.installPlanApproval }}
  name: {{ .Values.metadata.name }}
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.spec.startingCSV }}
