{{- $namespace := .Values.namespace | default "openshift-mtv" -}}

apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  name: {{ printf "%s-sc-rwx-px" .Release.Name }}
  namespace: {{ $namespace }}
spec:
  map:
    - destination:
        storageClass: {{ .Values.storageClass | default "px-rwx-rep2-netapp-fas8300" }}
      source:
        id: {{ .Values.datastoreId | default "datastore-1013" }}
  {{- template "mtv.provider" }}
