apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
  name: virtualization-operator
  namespace: {{ .Values.metadata.namespace }}
  {{- template "argocd.finalizer.labels"}}
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: openshift-cnv
  source:
    path: Charts/kubevirt
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  project: default
