apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/mtv-operator.openshift-mtv: ''
  name: mtv-operator
  namespace: openshift-mtv
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  channel: release-v2.4
  installPlanApproval: Automatic
  name: mtv-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: mtv-operator.v2.4.2

---

apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-wave-delay-
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "8"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: wait-pod
        image: perl
        command: ["sleep",  "120"]
      restartPolicy: Never
