kind: Project
apiVersion: project.openshift.io/v1
metadata:
  labels:
    argocd.argoproj.io/managed-by: "openshift-gitops"
  name: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec: {}
