apiVersion: batch/v1
kind: Job
metadata:
  name: sync_wave_delay
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: wait-60s
        image: perl
        command: ["sleep",  "60"]
      restartPolicy: Never
