apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodapp
spec:
  selector:
    matchLabels:
      app: prodapp
  template:
    metadata:
      labels:
        app: prodapp
    spec:
      containers:
      - name: prodapp
        image: https://quay.io/repository/rnare/liberty-rest:latest
        resources: {}
        ports:
        - containerPort: 9080
