apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: open-cluster-management-2w9m9
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  targetNamespaces:
    - open-cluster-management
