apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ocp4-jxkk4
    machine.openshift.io/cluster-api-machine-role: infra
    machine.openshift.io/cluster-api-machine-type: infra
  name: ocp4-jxkk4-infra
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp4-jxkk4
      machine.openshift.io/cluster-api-machineset: ocp4-jxkk4-infra
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp4-jxkk4
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: ocp4-jxkk4-infra
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
      providerSpec:
        value:
          cluster_id: 4623d003-2753-41e7-a16d-be106cd6622f
          userDataSecret:
            name: worker-user-data
          cpu:
            cores: 4
            sockets: 1
            threads: 1
          credentialsSecret:
            name: ovirt-credentials
          metadata:
          template_name: ocp4-jxkk4-rhcos
          memory_mb: 16348
          kind: OvirtMachineProviderSpec
          os_disk:
            size_gb: 120
          type: server
          id: ''
          apiVersion: ovirtproviderconfig.machine.openshift.io/v1beta1
