# Default values for nmstate Operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: kubernetes-nmstate-operator
  namespace: openshift-nmstate

spec:
  channel: stable
  installPlanApproval: Automatic
  startingCSV: kubernetes-nmstate-operator.4.15.0-202406060836
