apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.metadata.namespace }}-2w9m9
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  targetNamespaces:
    - {{ .Values.metadata.namespace }}
