- name: Main
  hosts: localhost
  tasks:
  - name: Load Plan
    include_vars:
      file: plan.yml
      name: plan

  - name: Load Workload
    include_vars:
      file: workload.yml
      name: workload

  - k8s_info:
      api_version: v1
      kind: Secret
      name: rhel8-ssh-credentials
      namespace: openshift-mtv
    register: user_cred
  # - debug: msg="{{ user_cred.resources[0].data.key | b64decode }}" # display the decoded key for debugging.


  - add_host:
      name: "{{ workload.vm.ipaddress }}"
      ansible_user: regis # VMs sudo username
      ansible_password: "{{ user_cred.resources[0].data.key | b64decode }}"
      groups: vms
  # - debug: msg="{{ workload.vm.ipaddress }}" # display the ip addresses for debugging.

- hosts: vms
  # debugger: on_unreachable
  tasks:
  # - name: Install cloud-init
  #   dnf:
  #     name:
  #     - cloud-init
  #     state: latest

  - name: Create Test File
    copy:
      dest: ~/test.txt
      content: " Hello World "
      mode: 0644
      
# Maybe I can create a post hook job to install a VMs guest tool in my VM to facilitate migration?
