apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  tokenConfig:
    accessTokenInactivityTimeout: 300s
  identityProviders:
  - htpasswd:
      fileData:
        name: localuser
    mappingMethod: claim
    name: localusers
    type: HTPasswd
