#autoSizingReserved: true   Kubelet default cpu & memory reserved is turned off and automatic resource allocation is enabled based on node capacity.
#maxPods: 500                Increase the maximum number of pods per node to 500
#nodeStatusMaxImages: -1     Set the maximum number of images to -1 (unlimited)
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: set-virt-values
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/master: ""
  kubeletConfig:
    autoSizingReserved: true 
    maxPods: 500         
    nodeStatusMaxImages: -1
    kubeAPIBurst: 200
    kubeAPIQPS: 100
