# Example of an nncp with sub interface and corresponding nad. Only one interface is involved here.
# kcs https://access.redhat.com/solutions/6990200

#                   [br-ex]--[eth0]                 
#                             [br-ex]--[eth0]
#                   [br10]--[eth0.100]--/ / /
#                   [br20]--[eth0.200]---/ /
#                   [br30]--[eth0.300]----/
      
   
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br10-policy 
spec:
  desiredState:
    interfaces:
      - name: br10
        type: linux-bridge 
        state: up 
        ipv4:
          enabled: false 
        bridge:
          options:
            stp:
              enabled: false 
          port:
            - name: bond0.188
      - name: bond0.188 
        type: vlan 
        state: up 
        vlan:
          base-iface: bond0
          id: 188

---
# There is no need to tag the vlan in the NAD anymore.
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "nad-188",
        "type": "bridge",
        "bridge": "br10",
        "ipam": {},
        "macspoofchk": true,
        "preserveDefaultVlan": false
    }
