apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: acm-observability0
      endpoint: s3.us-east-2.amazonaws.com 
      insecure: true
#      access_key: need secret here
#      secret_key: need secret here
