apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster-0
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  storage:
    deviceClasses:
      - thinPoolConfig:
          sizePercent: 90
          name: thin-pool-1
          overprovisionRatio: 10
        name: vg1
