{{- $namespace := .Values.namespace | default "openshift-mtv" -}}

apiVersion: forklift.konveyor.io/v1beta1
kind: NetworkMap
metadata:
  name: {{ printf "%s-vlanid-vm-name" .Release.Name }}
  namespace: {{ $namespace }}
spec:
  map:
    - destination:
        name: {{ .Values.networkDestinationName | default "br1-vlan2616-default" }}
        type: {{ .Values.networkDestinationType | default "multus" }}
        namespace: {{ .Values.networkDestinationNamespace | default "default" }}
      source:
        id: {{ .Values.networkSourceId | default "dvportgroup-15004" }}
        name: {{ .Values.networkSourceName | default "2616-mia-bcst-cl01-vds01-HVAdmin" }}
  {{- template "mtv.provider" }}
