apiVersion: forklift.konveyor.io/v1beta1
kind: NetworkMap
metadata:
  name: vlanid-vm-name- # need generated name for unique names
  namespace: openshift-mtv
spec:
  map:
    - destination:
        name: br1-vlan2616-default
        type: multus
        namespace: default
      source:
        id: dvportgroup-15004
        name: 2616-mia-bcst-cl01-vds01-HVAdmin 
    # - destination:
    #     type: multus
    #     name: <network_attachment_definition>  3 
    #     namespace: <network_attachment_definition_namespace>  4 
    #   source:
    #     id: <source_network_mor>
  provider:
    source:
      name: mia-vsphere
      namespace: openshift-mtv
    destination:
      name: host
      namespace: openshift-mtv
