apiVersion: operators.coreos.com/v1beta1
kind: Subscription
metadata:
  name: hco-operatorhub
  namespace: openshift-cnv
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
  name: kubevirt-hyperconverged
  startingCSV: kubevirt-hyperconverged-operator.v4.13.3
  channel: "stable"
---

apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-wave-delay-
  namespace: openshift-cnv
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "14"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: wait-pod
        image: perl
        command: ["sleep",  "180"]
      restartPolicy: Never
