apiVersion: cluster.open-cluster-management.io/v1beta2
kind: Placement
metadata:
  name: all-openshift-clusters
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: vendor
          operator: "In"
          values:
          - OpenShift
